spring:
  profiles:
    active:
      - dev
---
server:
  port: 7001

spring:
  profiles: dev #开发环境
  application:
    name: servercloud-config-eureka-client

eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: true #注册自己
    fetch-registry: true #提供服务，检索服务
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
---
server:
  port: 7001
spring:
  profiles: test #测试环境
  application:
    name: servercloud-config-client
eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: true #注册自己
    fetch-registry: true #提供服务，检索服务
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/